In [1]:
import sqlite3
import pandas as pd

# Connect to SQLite database (new file for Day 25)
conn = sqlite3.connect("Day025.db")
cursor = conn.cursor()

# Drop tables if they exist
cursor.execute("DROP TABLE IF EXISTS employees")
cursor.execute("DROP TABLE IF EXISTS departments")

# Create employees table
cursor.execute("""
CREATE TABLE employees (
    emp_id INTEGER PRIMARY KEY,
    name TEXT,
    dept_id INTEGER,
    salary INTEGER
)
""")

# Create departments table
cursor.execute("""
CREATE TABLE departments (
    dept_id INTEGER PRIMARY KEY,
    dept_name TEXT
)
""")

# Insert sample data
employees_data = [
    (1, 'Amit', 1, 60000),
    (2, 'Neha', 2, 55000),
    (3, 'Raj', 3, 70000),
    (4, 'Simran', 1, 65000),
    (5, 'Karan', 4, 50000),
    (6, 'Priya', 3, 72000),
    (7, 'Arjun', 2, 48000),
    (8, 'Meera', 1, 68000),
    (9, 'Rohit', 3, 75000),
    (10, 'Sneha', 4, 52000)
]
cursor.executemany("INSERT INTO employees VALUES (?, ?, ?, ?)", employees_data)

departments_data = [
    (1, 'IT'),
    (2, 'HR'),
    (3, 'Finance'),
    (4, 'Marketing')
]
cursor.executemany("INSERT INTO departments VALUES (?, ?)", departments_data)

conn.commit()

In [2]:
# Show all employees with their details
pd.read_sql("SELECT * FROM employees", conn)

   emp_id    name  dept_id  salary
0       1    Amit        1   60000
1       2    Neha        2   55000
2       3     Raj        3   70000
3       4  Simran        1   65000
4       5   Karan        4   50000
5       6   Priya        3   72000
6       7   Arjun        2   48000
7       8   Meera        1   68000
8       9   Rohit        3   75000
9      10   Sneha        4   52000

In [3]:
# Show employees in IT department with salary > 60,000, sorted by salary descending
pd.read_sql("""
SELECT name, salary
FROM employees
WHERE dept_id = 1 AND salary > 60000
ORDER BY salary DESC
""", conn)

     name  salary
0   Meera   68000
1  Simran   65000

In [4]:
# Show employee names with their department names
pd.read_sql("""
SELECT employees.name, departments.dept_name, employees.salary
FROM employees
INNER JOIN departments ON employees.dept_id = departments.dept_id
""", conn)

     name  dept_name  salary
0    Amit         IT   60000
1    Neha         HR   55000
2     Raj    Finance   70000
3  Simran         IT   65000
4   Karan  Marketing   50000
5   Priya    Finance   72000
6   Arjun         HR   48000
7   Meera         IT   68000
8   Rohit    Finance   75000
9   Sneha  Marketing   52000

In [5]:
# Show average salary per department
pd.read_sql("""
SELECT departments.dept_name, AVG(employees.salary) AS avg_salary
FROM employees
INNER JOIN departments ON employees.dept_id = departments.dept_id
GROUP BY departments.dept_name
""", conn)

   dept_name    avg_salary
0    Finance  72333.333333
1         HR  51500.000000
2         IT  64333.333333
3  Marketing  51000.000000

In [6]:
# Show departments where average salary > 60,000
pd.read_sql("""
SELECT departments.dept_name, AVG(employees.salary) AS avg_salary
FROM employees
INNER JOIN departments ON employees.dept_id = departments.dept_id
GROUP BY departments.dept_name
HAVING AVG(employees.salary) > 60000
""", conn)

  dept_name    avg_salary
0   Finance  72333.333333
1        IT  64333.333333