In [ ]:
import sqlite3
import pandas as pd

# Connect to SQLite database (reuse day21.db or create new day22.db)
conn = sqlite3.connect("Day22.db")
cursor = conn.cursor()

# Drop table if exists (fresh start)
cursor.execute("DROP TABLE IF EXISTS employees")

# Create employees table
cursor.execute("""
CREATE TABLE employees (
    emp_id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    salary INTEGER
)
""")

# Insert sample employee data
data = [
    (1, 'Amit', 'IT', 60000),
    (2, 'Neha', 'HR', 55000),
    (3, 'Raj', 'Finance', 70000),
    (4, 'Simran', 'IT', 65000),
    (5, 'Karan', 'Marketing', 50000),
    (6, 'Priya', 'Finance', 72000),
    (7, 'Arjun', 'HR', 48000),
    (8, 'Meera', 'IT', 68000)
]
cursor.executemany("INSERT INTO employees VALUES (?, ?, ?, ?)", data)
conn.commit()

In [ ]:
# WHERE filters rows based on a condition

# 1. Employees with salary greater than 60,000
pd.read_sql("SELECT * FROM employees WHERE salary > 60000", conn)

# 2. Employees from IT department only
pd.read_sql("SELECT * FROM employees WHERE department = 'IT'", conn)

# 3. Employees with salary between 50,000 and 65,000
pd.read_sql("SELECT * FROM employees WHERE salary BETWEEN 50000 AND 65000", conn)

   emp_id    name department  salary
0       1    Amit         IT   60000
1       2    Neha         HR   55000
2       4  Simran         IT   65000
3       5   Karan  Marketing   50000

In [ ]:
# ORDER BY sorts rows in ascending (ASC) or descending (DESC) order

# 1. Employees sorted by salary (lowest to highest)
pd.read_sql("SELECT name, salary FROM employees ORDER BY salary ASC", conn)

# 2. Employees sorted by salary (highest to lowest)
pd.read_sql("SELECT name, salary FROM employees ORDER BY salary DESC", conn)

# 3. Employees sorted by department, then salary
pd.read_sql("SELECT name, department, salary FROM employees ORDER BY department ASC, salary DESC", conn)

     name department  salary
0   Priya    Finance   72000
1     Raj    Finance   70000
2    Neha         HR   55000
3   Arjun         HR   48000
4   Meera         IT   68000
5  Simran         IT   65000
6    Amit         IT   60000
7   Karan  Marketing   50000