In [ ]:
import sqlite3
import pandas as pd

# Connect to a new SQLite database file
conn = sqlite3.connect("Day21.db")
cursor = conn.cursor()

# Drop table if it already exists
cursor.execute("DROP TABLE IF EXISTS employees")

# Create employees table
cursor.execute("""
CREATE TABLE employees (
    emp_id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    salary INTEGER
)
""")

In [ ]:
# Employee data
data = [
    (1, 'Amit', 'IT', 60000),
    (2, 'Neha', 'HR', 55000),
    (3, 'Raj', 'Finance', 70000),
    (4, 'Simran', 'IT', 65000),
    (5, 'Karan', 'Marketing', 50000),
    (6, 'Priya', 'Finance', 72000),
    (7, 'Arjun', 'HR', 48000),
    (8, 'Meera', 'IT', 68000)
]

# Insert rows
cursor.executemany("INSERT INTO employees VALUES (?, ?, ?, ?)", data)
conn.commit()

In [ ]:
# Fetching ALL rows and ALL columns from the employees table
pd.read_sql("SELECT * FROM employees", conn)

   emp_id    name department  salary
0       1    Amit         IT   60000
1       2    Neha         HR   55000
2       3     Raj    Finance   70000
3       4  Simran         IT   65000
4       5   Karan  Marketing   50000
5       6   Priya    Finance   72000
6       7   Arjun         HR   48000
7       8   Meera         IT   68000

In [ ]:
# Fetching only the name and salary columns
pd.read_sql("SELECT name, salary FROM employees", conn)

     name  salary
0    Amit   60000
1    Neha   55000
2     Raj   70000
3  Simran   65000
4   Karan   50000
5   Priya   72000
6   Arjun   48000
7   Meera   68000

In [ ]:
# Renaming columns to make them more readable
pd.read_sql("SELECT name AS employee_name, salary AS monthly_salary FROM employees", conn)

  employee_name  monthly_salary
0          Amit           60000
1          Neha           55000
2           Raj           70000
3        Simran           65000
4         Karan           50000
5         Priya           72000
6         Arjun           48000
7         Meera           68000

In [ ]:
# Fetching unique department names (removes duplicates)
pd.read_sql("SELECT DISTINCT department FROM employees", conn)

  department
0         IT
1         HR
2    Finance
3  Marketing

In [ ]:
# Fetching only the first 3 rows from the table
pd.read_sql("SELECT * FROM employees LIMIT 3", conn)

   emp_id  name department  salary
0       1  Amit         IT   60000
1       2  Neha         HR   55000
2       3   Raj    Finance   70000