In [1]:
import sqlite3
import pandas as pd

# Connect to SQLite database (new file for Day 24)
conn = sqlite3.connect("day24.db")
cursor = conn.cursor()

# Drop table if exists (fresh start)
cursor.execute("DROP TABLE IF EXISTS employees")

# Create employees table
cursor.execute("""
CREATE TABLE employees (
    emp_id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    salary INTEGER
)
""")

# Insert sample employee data
data = [
    (1, 'Amit', 'IT', 60000),
    (2, 'Neha', 'HR', 55000),
    (3, 'Raj', 'Finance', 70000),
    (4, 'Simran', 'IT', 65000),
    (5, 'Karan', 'Marketing', 50000),
    (6, 'Priya', 'Finance', 72000),
    (7, 'Arjun', 'HR', 48000),
    (8, 'Meera', 'IT', 68000),
    (9, 'Rohit', 'Finance', 75000),
    (10, 'Sneha', 'Marketing', 52000)
]
cursor.executemany("INSERT INTO employees VALUES (?, ?, ?, ?)", data)
conn.commit()

In [2]:
# GROUP BY groups rows based on a column
# Example: group employees by department and calculate average salary

pd.read_sql("""
SELECT department, AVG(salary) AS avg_salary
FROM employees
GROUP BY department
""", conn)

  department    avg_salary
0    Finance  72333.333333
1         HR  51500.000000
2         IT  64333.333333
3  Marketing  51000.000000

In [3]:
# HAVING filters groups after aggregation
# Example: show only departments with average salary greater than 60,000

pd.read_sql("""
SELECT department, AVG(salary) AS avg_salary
FROM employees
GROUP BY department
HAVING AVG(salary) > 60000
""", conn)

  department    avg_salary
0    Finance  72333.333333
1         IT  64333.333333